/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-08-08 16:32:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.List;

public final class Display_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Employee Records</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("margin: 0;\r\n");
      out.write("background-color: #d7c288;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("  font-family: arial, sans-serif;\r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td, th {\r\n");
      out.write("  border: 1px solid #dddddd;\r\n");
      out.write("  text-align: left;\r\n");
      out.write("  padding: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr:nth-child(even) {\r\n");
      out.write("  background-color: #dddddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search{\r\n");
      out.write("display: flex;\r\n");
      out.write("justify-content: space-between;\r\n");
      out.write("margin-top: 20px;\r\n");
      out.write("margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a{\r\n");
      out.write("text-decoration: none;\r\n");
      out.write("color: blue;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".Btn{\r\n");
      out.write("\r\n");
      out.write("display: flex;\r\n");
      out.write("justify-content: center;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button{\r\n");
      out.write("    width: 150px;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    background: #669999;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".det{\r\n");
      out.write("\r\n");
      out.write("width:300px;\r\n");
      out.write("background-color: black;\r\n");
      out.write("color: white;\r\n");
      out.write("display: flex;\r\n");
      out.write("justify-content: center;\r\n");
      out.write("border-radius: 70px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".emp{\r\n");
      out.write("\r\n");
      out.write("display: flex;\r\n");
      out.write("justify-content: center;\r\n");
      out.write("background-color: #9d830b;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover{\r\n");
      out.write("background-color: grey;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"emp\">\r\n");
      out.write("<div class=\"det\">\r\n");
      out.write("<h3>Employee Details</h3>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"search\">\r\n");
      out.write("<div class=\"sear\">\r\n");
      out.write("\r\n");
      out.write("<label for=\"searchColumn\" style=\"font-weight: bold;\">Search in: </label>\r\n");
      out.write("<select id=\"searchColumn\">\r\n");
      out.write("  <option value=\"0\">Emp_id</option>\r\n");
      out.write("  <option value=\"1\">Emp_name</option>\r\n");
      out.write("  <option value=\"2\">Designation</option>\r\n");
      out.write("  <option value=\"3\">Department</option>\r\n");
      out.write("  <option value=\"4\">Joined_date</option>\r\n");
      out.write("  <option value=\"5\">Salary</option>\r\n");
      out.write("  <option value=\"6\">Addressline1</option>\r\n");
      out.write("  <option value=\"7\">Addressline2</option>\r\n");
      out.write("  <option value=\"8\">City</option>\r\n");
      out.write("  <option value=\"9\">State</option>\r\n");
      out.write("  <option value=\"10\">Country</option>\r\n");
      out.write("</select>\r\n");
      out.write("<input type=\"text\" id=\"searchInput\" placeholder=\"Search\">\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write(" <label for=\"searchColumn\" style=\"font-weight: bold;\">Global Search:</label> <input type=\"text\" id=\"searchInput1\" placeholder=\"Search...\">\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write(" <table border=\"1\" id=\"employeeTable\">\r\n");
      out.write("        <tr>\r\n");
      out.write("            <th>Emp_id</th>\r\n");
      out.write("            <th>Emp_name</th>\r\n");
      out.write("            <th>Designation</th>\r\n");
      out.write("            <th>Department</th>\r\n");
      out.write("            <th>Joined_date</th>\r\n");
      out.write("            <th>Salary</th>\r\n");
      out.write("            <th>Addressline1</th>\r\n");
      out.write("            <th>Addressline2</th>\r\n");
      out.write("            <th>City</th>\r\n");
      out.write("            <th>State</th>\r\n");
      out.write("            <th>Country</th>\r\n");
      out.write("             <th>Edit</th>\r\n");
      out.write("            <th>Delete</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("        ");

        List<List<String>> ans = new ArrayList<>();
        ans = (List) request.getAttribute("displayList");
        
        
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        ");
 
        if(ans!=null){
         int j=0;
        for (int i = 0; i < ans.size(); i++) {  
        	   j=0; 
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>");
      out.print( ans.get(i).get(j++) );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( ans.get(i).get(j++) );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( ans.get(i).get(j++) );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( ans.get(i).get(j++) );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( ans.get(i).get(j++) );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( ans.get(i).get(j++) );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( ans.get(i).get(j++) );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( ans.get(i).get(j++) );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( ans.get(i).get(j++) );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( ans.get(i).get(j++) );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( ans.get(i).get(j++) );
      out.write("</td>\r\n");
      out.write("                <td><a style=\"color: black; font-weight: bold;\"  href=\"UpdateEmployee.jsp?id=");
      out.print( ans.get(i).get(0) );
      out.write("\">Edit</a></td>\r\n");
      out.write("                 <td><a style=\"color: black;font-weight: bold;\" href=\"DeleteEmployee?id=");
      out.print(ans.get(i).get(0));
      out.write("\">Delete</a></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("       ");
} 
      out.write("  \r\n");
      out.write("    </table>\r\n");
      out.write("    <br>\r\n");
      out.write("    <div class=\"Btn\">\r\n");
      out.write("    \r\n");
      out.write("    <form method=\"post\" action=\"userDashboard.jsp\">\r\n");
      out.write("     <button type=\"submit\">Back</button>\r\n");
      out.write("    \r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  // Function to filter the table rows based on the search input\r\n");
      out.write("  \r\n");
      out.write("  $(document).ready(function() {\r\n");
      out.write("    // Get the table and the input field\r\n");
      out.write("    var table = $(\"#employeeTable\");\r\n");
      out.write("    var input = $(\"#searchInput1\");\r\n");
      out.write("\r\n");
      out.write("    // Add an event listener to the input field for handling the search\r\n");
      out.write("    input.on(\"keyup\", function() {\r\n");
      out.write("        var searchValue = this.value.toLowerCase();\r\n");
      out.write("        // Loop through all rows in the table body\r\n");
      out.write("        table.find(\"tbody tr\").each(function() {\r\n");
      out.write("            var row = $(this);\r\n");
      out.write("            var matchFound = false;\r\n");
      out.write("            // Loop through all columns in the row\r\n");
      out.write("            row.find(\"td\").each(function() {\r\n");
      out.write("                var cellText = $(this).text().toLowerCase();\r\n");
      out.write("                if (cellText.includes(searchValue)) {\r\n");
      out.write("                    matchFound = true;\r\n");
      out.write("                    return false; // Break the inner loop if match found in any cell\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("            // Show or hide the row based on matchFound\r\n");
      out.write("            row.toggle(matchFound);\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write(" function filterTable() {\r\n");
      out.write("    var input, filter, table, tr, td, i, columnIndex, txtValue;\r\n");
      out.write("    input = document.getElementById(\"searchInput\");\r\n");
      out.write("    filter = input.value.toUpperCase();\r\n");
      out.write("    table = document.getElementById(\"employeeTable\");\r\n");
      out.write("    tr = table.getElementsByTagName(\"tr\");\r\n");
      out.write("    columnIndex = parseInt(document.getElementById(\"searchColumn\").value);\r\n");
      out.write("\r\n");
      out.write("    for (i = 1; i < tr.length; i++) { // Start from index 1 to skip the header row\r\n");
      out.write("      td = tr[i].getElementsByTagName(\"td\")[columnIndex];\r\n");
      out.write("\r\n");
      out.write("      if (td) {\r\n");
      out.write("        txtValue = td.textContent || td.innerText;\r\n");
      out.write("        if (txtValue.toUpperCase().indexOf(filter) > -1) {\r\n");
      out.write("          tr[i].style.display = \"\"; // Show the row if it matches the search query\r\n");
      out.write("        } else {\r\n");
      out.write("          tr[i].style.display = \"none\"; // Hide the row if it does not match the search query\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  // Attach event listeners to trigger filtering when the search input or select changes\r\n");
      out.write("  document.getElementById(\"searchInput\").addEventListener(\"keyup\", filterTable);\r\n");
      out.write("  document.getElementById(\"searchColumn\").addEventListener(\"change\", filterTable);\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
