/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-08-08 16:01:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>UserRegistration Page</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("<\r\n");
      out.write("link href =\"https: //fonts.googleapis.com /css ?family =Roboto:300, 400,\r\n");
      out.write("	500, 700 \" rel =\"stylesheet \"> <link rel =\"stylesheet \" href =\"https:\r\n");
      out.write("	//use.fontawesome.com /releases /v5.5.0 /css /all.css \" integrity =\"sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU\r\n");
      out.write("	\" crossorigin =\"anonymous \"> <style>html, body {\r\n");
      out.write("	min-height: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body, div, form, input, select, textarea, label, p {\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	font-family: Roboto, Arial, sans-serif;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	color: #666;\r\n");
      out.write("	line-height: 22px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	font-size: 34px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	z-index: 2;\r\n");
      out.write("	line-height: 83px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("textarea {\r\n");
      out.write("	width: calc(100% - 12px);\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".testbox {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	height: inherit;\r\n");
      out.write("	width: 500px;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	background-color: black;\r\n");
      out.write("	background-image: url(\"images/we.webp\");\r\n");
      out.write("	background-position: center;\r\n");
      out.write("	background-repeat: no-repeat;\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	border-radius: 6px;\r\n");
      out.write("	background: #fff;\r\n");
      out.write("	box-shadow: 0 0 8px #669999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".banner {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	height: 300px;\r\n");
      out.write("	background-image: url(\"images/we.webp\");\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".banner::after {\r\n");
      out.write("	content: \"\";\r\n");
      out.write("	background-color: rgba(0, 0, 0, 0.2);\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input, select, textarea {\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	border: 1px solid #ccc;\r\n");
      out.write("	border-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("	width: calc(100% - 10px);\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"date\"] {\r\n");
      out.write("	padding: 4px 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("textarea {\r\n");
      out.write("	width: calc(100% - 12px);\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item:hover p, .item:hover i, .question:hover p, .question label:hover,\r\n");
      out.write("	input:hover::placeholder {\r\n");
      out.write("	color: #669999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item input:hover, .item select:hover, .item textarea:hover {\r\n");
      out.write("	border: 1px solid transparent;\r\n");
      out.write("	box-shadow: 0 0 3px 0 #669999;\r\n");
      out.write("	color: #669999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item span {\r\n");
      out.write("	color: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".item i, input[type=\"date\"]::-webkit-calendar-picker-indicator {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	color: #a3c2c2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item i {\r\n");
      out.write("	right: 1%;\r\n");
      out.write("	top: 30px;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("label.radio {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin: 5px 20px 15px 0;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".question span {\r\n");
      out.write("	margin-left: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".question-answer label {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label.radio:before {\r\n");
      out.write("	content: \"\";\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 17px;\r\n");
      out.write("	height: 17px;\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("	border: 2px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=radio]:checked+label:before, label.radio:hover:before {\r\n");
      out.write("	border: 2px solid #669999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label.radio:after {\r\n");
      out.write("	content: \"\";\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 6px;\r\n");
      out.write("	left: 5px;\r\n");
      out.write("	width: 8px;\r\n");
      out.write("	height: 4px;\r\n");
      out.write("	border: 3px solid #669999;\r\n");
      out.write("	border-top: none;\r\n");
      out.write("	border-right: none;\r\n");
      out.write("	transform: rotate(-45deg);\r\n");
      out.write("	opacity: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=radio]:checked+label:after {\r\n");
      out.write("	opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".flax {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-block {\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	background: #669999;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button:hover {\r\n");
      out.write("	background: #a3c2c2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 568px) {\r\n");
      out.write("	.name-item, .city-item {\r\n");
      out.write("		display: flex;\r\n");
      out.write("		flex-wrap: wrap;\r\n");
      out.write("		justify-content: space-between;\r\n");
      out.write("	}\r\n");
      out.write("	.name-item input, .name-item div {\r\n");
      out.write("		width: calc(50% - 20px);\r\n");
      out.write("	}\r\n");
      out.write("	.name-item div input {\r\n");
      out.write("		width: 97%;\r\n");
      out.write("	}\r\n");
      out.write("	.name-item div label {\r\n");
      out.write("		display: block;\r\n");
      out.write("		padding-bottom: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	h1{\r\n");
      out.write("	color:#312433;}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head{\r\n");
      out.write("display: flex;\r\n");
      out.write("justify-content: center;\r\n");
      out.write("}\r\n");
      out.write(".err{\r\n");
      out.write("margin:0;\r\n");
      out.write("display:flex;\r\n");
      out.write("justify-content: center;\r\n");
      out.write("color:red;\r\n");
      out.write("font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

	String nameV = (String) request.getAttribute("name");
	String numberV = (String) request.getAttribute("number");
	String emailV = (String) request.getAttribute("email");
	String passV = (String) request.getAttribute("password");
	String con_passV = (String) request.getAttribute("conPass");
	String namevalue = (String) request.getAttribute("user");
	String number_value = (String) request.getAttribute("mob_no");
	String email_value = (String) request.getAttribute("email_id");
	String pass_value = (String) request.getAttribute("pass");
	String cpass_value = (String) request.getAttribute("Cpass");
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"text\">\r\n");
      out.write("	\r\n");
      out.write("		<div class=\"testbox\">\r\n");
      out.write("			<form method=\"post\" action=\"Servlett\">\r\n");
      out.write("				<div class=\"banner\">\r\n");
      out.write("					<h1>User Registration</h1>\r\n");
      out.write("				</div>\r\n");
      out.write("							 <div class=\"err\">\r\n");
      out.write("    <h4>\r\n");
      out.write("        ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("              ");
      out.print( request.getAttribute("error") );
      out.write("\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </h4>\r\n");
      out.write("</div>\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("				\r\n");
      out.write("					<label for=\"name\">Name<span>*</span></label> <input id=\"name\"\r\n");
      out.write("						type=\"text\" name=\"username\"\r\n");
      out.write("						value=\"");
      out.print(namevalue == null ? "" : namevalue);
      out.write("\"> <span\r\n");
      out.write("						class=\"error\"> ");
      out.print(nameV == null ? "" : nameV);
      out.write("\r\n");
      out.write("					</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<label for=\"email\">Email Address<span>*</span></label> <input\r\n");
      out.write("						id=\"email\" type=\"email\" name=\"email_\"\r\n");
      out.write("						value=\"");
      out.print(email_value == null ? "" : email_value);
      out.write("\"> <span\r\n");
      out.write("						class=\"error\"> ");
      out.print(emailV == null ? "" : emailV);
      out.write("\r\n");
      out.write("					</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<label for=\"phone\">Phone<span>*</span></label> <input id=\"phone\"\r\n");
      out.write("						type=\"number\" placeholder=\"(XXX) XXX-XXXX\" name=\"mob\"\r\n");
      out.write("						value=\"");
      out.print(number_value == null ? "" : number_value);
      out.write("\">\r\n");
      out.write("					<span class=\"error\"> ");
      out.print(numberV == null ? "" : numberV);
      out.write("\r\n");
      out.write("					</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<label for=\"password\">Password<span>*</span></label> <input\r\n");
      out.write("						id=\"password\" type=\"password\" name=\"pass\"\r\n");
      out.write("						placeholder=\"Enter your password\"\r\n");
      out.write("						value=\"");
      out.print(pass_value == null ? "" : pass_value);
      out.write("\">\r\n");
      out.write("						\r\n");
      out.write("						 <span\r\n");
      out.write("						class=\"error\"> ");
      out.print(passV == null ? "" : passV);
      out.write("\r\n");
      out.write("					</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<label for=\"conpass\">Confirm Password<span>*</span></label> <input\r\n");
      out.write("						id=\"conpass\" type=\"password\" name=\"confirmpass\"\r\n");
      out.write("						placeholder=\"Confirm password\"\r\n");
      out.write("						value=\"");
      out.print(cpass_value == null ? "" : cpass_value);
      out.write("\"> \r\n");
      out.write("						\r\n");
      out.write("						<span\r\n");
      out.write("						class=\"error\"> ");
      out.print(con_passV == null ? "" : con_passV);
      out.write("\r\n");
      out.write("					</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"btn-block\">\r\n");
      out.write("					<button type=\"submit\" name=\"action\" value=\"reg\">Register</button>\r\n");
      out.write("					<button type=\"submit\" name=\"action\" value=\"log\">Login</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("  var error = '");
      out.print( request.getAttribute("error") );
      out.write("';\r\n");
      out.write("\r\n");
      out.write("  if (error) {\r\n");
      out.write("    var fieldToFocus = '");
      out.print( request.getAttribute("setFocus") );
      out.write("'; // Replace with the actual field ID\r\n");
      out.write("    document.getElementById(fieldToFocus).focus();\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  function togglePasswordVisibility() {\r\n");
      out.write("      var passwordField = document.getElementById('password');\r\n");
      out.write("      var eyeIcon = document.querySelector('.toggle-password');\r\n");
      out.write("\r\n");
      out.write("      if (passwordField.type === 'password') {\r\n");
      out.write("          passwordField.type = 'text';\r\n");
      out.write("          eyeIcon.classList.remove('fa-eye');\r\n");
      out.write("          eyeIcon.classList.add('fa-eye-slash');\r\n");
      out.write("      } else {\r\n");
      out.write("          passwordField.type = 'password';\r\n");
      out.write("          eyeIcon.classList.remove('fa-eye-slash');\r\n");
      out.write("          eyeIcon.classList.add('fa-eye');\r\n");
      out.write("      }\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
