/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-08-08 16:33:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import utils.DbConnection;
import java.sql.Connection;

public final class UpdateEmployee_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("utils.DbConnection");
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Employee Update Page</title>\r\n");
      out.write("<style>\r\n");
      out.write("<\r\n");
      out.write("link href =\"https: //fonts.googleapis.com /css ?family =Roboto:300, 400,\r\n");
      out.write("	500, 700 \" rel =\"stylesheet \"> <link rel =\"stylesheet \" href =\"https:\r\n");
      out.write("	//use.fontawesome.com /releases /v5.5.0 /css /all.css \" integrity =\"sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU\r\n");
      out.write("	 \" crossorigin =\"anonymous \"> <style>html, body {\r\n");
      out.write("	min-height: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body, div, form, input, select, textarea, label, p {\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	font-family: Roboto, Arial, sans-serif;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	color: #666;\r\n");
      out.write("	line-height: 22px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	font-size: 34px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	z-index: 2;\r\n");
      out.write("	line-height: 83px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("textarea {\r\n");
      out.write("	width: calc(100% - 12px);\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".testbox {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	height: inherit;\r\n");
      out.write("	width: 500px;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	background-color: black;\r\n");
      out.write("	background-image: url(\"images/we.webp\");\r\n");
      out.write("	background-position: center;\r\n");
      out.write("	background-repeat: no-repeat;\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	border-radius: 6px;\r\n");
      out.write("	background: #fff;\r\n");
      out.write("	box-shadow: 0 0 8px #669999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".banner {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	height: 300px;\r\n");
      out.write("	background-image: url(\"images/we.webp\");\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".banner::after {\r\n");
      out.write("	content: \"\";\r\n");
      out.write("	background-color: rgba(0, 0, 0, 0.2);\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input, select, textarea {\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	border: 1px solid #ccc;\r\n");
      out.write("	border-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("	width: calc(100% - 10px);\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"date\"] {\r\n");
      out.write("	padding: 4px 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("textarea {\r\n");
      out.write("	width: calc(100% - 12px);\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item:hover p, .item:hover i, .question:hover p, .question label:hover,\r\n");
      out.write("	input:hover::placeholder {\r\n");
      out.write("	color: #669999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item input:hover, .item select:hover, .item textarea:hover {\r\n");
      out.write("	border: 1px solid transparent;\r\n");
      out.write("	box-shadow: 0 0 3px 0 #669999;\r\n");
      out.write("	color: #669999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item span {\r\n");
      out.write("	color: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item i, input[type=\"date\"]::-webkit-calendar-picker-indicator {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	color: #a3c2c2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item i {\r\n");
      out.write("	right: 1%;\r\n");
      out.write("	top: 30px;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label.radio {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin: 5px 20px 15px 0;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".question span {\r\n");
      out.write("	margin-left: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".question-answer label {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label.radio:before {\r\n");
      out.write("	content: \"\";\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 17px;\r\n");
      out.write("	height: 17px;\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("	border: 2px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=radio]:checked+label:before, label.radio:hover:before {\r\n");
      out.write("	border: 2px solid #669999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label.radio:after {\r\n");
      out.write("	content: \"\";\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 6px;\r\n");
      out.write("	left: 5px;\r\n");
      out.write("	width: 8px;\r\n");
      out.write("	height: 4px;\r\n");
      out.write("	border: 3px solid #669999;\r\n");
      out.write("	border-top: none;\r\n");
      out.write("	border-right: none;\r\n");
      out.write("	transform: rotate(-45deg);\r\n");
      out.write("	opacity: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=radio]:checked+label:after {\r\n");
      out.write("	opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".flax {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-block {\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	background: #669999;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button:hover {\r\n");
      out.write("	background: #a3c2c2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 568px) {\r\n");
      out.write("	.name-item, .city-item {\r\n");
      out.write("		display: flex;\r\n");
      out.write("		flex-wrap: wrap;\r\n");
      out.write("		justify-content: space-between;\r\n");
      out.write("	}\r\n");
      out.write("	.name-item input, .name-item div {\r\n");
      out.write("		width: calc(50% - 20px);\r\n");
      out.write("	}\r\n");
      out.write("	.name-item div input {\r\n");
      out.write("		width: 97%;\r\n");
      out.write("	}\r\n");
      out.write("	.name-item div label {\r\n");
      out.write("		display: block;\r\n");
      out.write("		padding-bottom: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	h1 {\r\n");
      out.write("		color: #312433;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".head {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".err{\r\n");
      out.write("margin:0;\r\n");
      out.write("display:flex;\r\n");
      out.write("justify-content: center;\r\n");
      out.write("color:red;\r\n");
      out.write("font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	String empvalue = (String) request.getAttribute("emp_id");
	String namevalue = (String) request.getAttribute("emp_name");
	String desigvalue = (String) request.getAttribute("designation");
	String depvalue = (String) request.getAttribute("department");
	String joined_date_value = (String) request.getAttribute("joined_date");
	String salaryvalue = (String) request.getAttribute("salary");
	String adr1_value = (String) request.getAttribute("addressline1");
	String adr2_value = (String) request.getAttribute("addressline2");
	String city_value = (String) request.getAttribute("city");
	String state_value = (String) request.getAttribute("state");
	String country_value = (String) request.getAttribute("country");
	String status = "0";
	if (request.getAttribute("status") != null) {
		status = (String) request.getAttribute("status");
	}
	String emp_id = request.getParameter("id");
	request.setAttribute("EID", emp_id);
	System.out.println("Emp_iddd1:" + emp_id);
	if (emp_id == null) {
		emp_id = (String) request.getAttribute("emp_id");
		System.out.println("Emp_iddd1:" + emp_id);
	}

	String empV = (String) request.getAttribute("emp_idErr");
	String nameV = (String) request.getAttribute("emp_nameErr");
	String desigV = (String) request.getAttribute("desigErr");
	String depV = (String) request.getAttribute("depErr");
	String joinedV = (String) request.getAttribute("joined_dateErr");
	String salaryV = (String) request.getAttribute("salaryErr");
	String adr1V = (String) request.getAttribute("adr1Err");
	String adr2V = (String) request.getAttribute("adr2Err");
	String cityV = (String) request.getAttribute("cityErr");
	String stateV = (String) request.getAttribute("stateErr");
	String countryV = (String) request.getAttribute("countryErr");
	System.out.println("Emp_id:" + emp_id);
	HttpSession sess = request.getSession(true);
	int user_id = (int) sess.getAttribute("userID");
	if (!status.equals("1")) {
		try (Connection con = DbConnection.getConnection()) {

			PreparedStatement ps1 = con.prepareStatement("select * from employee_master where user_id =? and emp_id=?");

			/* 	ps1.setInt(1, user_id);
			ps1.setString(2, emp_id);
			ResultSet rs = ps1.executeQuery();
			
			
			while(rs.next()){
			
			
			
			
			System.out.println("mast_code:"+mast);
			}
			*/
			ps1.setInt(1, user_id);
			ps1.setString(2, emp_id);
			ResultSet rs1 = ps1.executeQuery();
			int mast = 0;
			while (rs1.next()) {
		mast = rs1.getInt("mast_code");
		empvalue = rs1.getString("emp_id");
		namevalue = rs1.getString("emp_name");
		desigvalue = rs1.getString("designation");
		depvalue = rs1.getString("department");
		joined_date_value = rs1.getString("joined_date");
		salaryvalue = rs1.getString("salary");

			}

			PreparedStatement ps2 = con.prepareStatement("select * from employee_detail where emp_code =?");
			ps2.setInt(1, mast);
			ResultSet rs2 = ps2.executeQuery();
			while (rs2.next()) {

		adr1_value = rs2.getString("addressline1");
		adr2_value = rs2.getString("addressline2");
		city_value = rs2.getString("city");
		state_value = rs2.getString("state");
		country_value = rs2.getString("country");

			}

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"text\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"testbox\">\r\n");
      out.write("			<form method=\"post\" action=\"updateEmployee\">\r\n");
      out.write("				<div class=\"banner\">\r\n");
      out.write("					<h1>Update Employee</h1>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"err\">\r\n");
      out.write("					<h4>\r\n");
      out.write("						");

						if (request.getAttribute("error") != null) {
						
      out.write("\r\n");
      out.write("						");
      out.print(request.getAttribute("error"));
      out.write("\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<label for=\"id\">Emp_Id<span>*</span></label> <input id=\"id\"\r\n");
      out.write("						type=\"text\" name=\"emp_id\"\r\n");
      out.write("						value=\"");
      out.print(empvalue == null ? "" : empvalue);
      out.write("\"> <span\r\n");
      out.write("						class=\"error\"> ");
      out.print(empV == null ? "" : empV);
      out.write("\r\n");
      out.write("					</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<label for=\"emp_name\">Emp_Name<span>*</span></label> <input\r\n");
      out.write("						id=\"empname\" type=\"text\" name=\"emp_name\"\r\n");
      out.write("						value=\"");
      out.print(namevalue == null ? "" : namevalue);
      out.write("\"> <span\r\n");
      out.write("						class=\"error\"> ");
      out.print(nameV == null ? "" : nameV);
      out.write("\r\n");
      out.write("					</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<label for=\"desig\">Designation<span>*</span></label> <input\r\n");
      out.write("						id=\"desig\" type=\"text\" placeholder=\"Designation\"\r\n");
      out.write("						name=\"designation\"\r\n");
      out.write("						value=\"");
      out.print(desigvalue == null ? "" : desigvalue);
      out.write("\"> <span\r\n");
      out.write("						class=\"error\"> ");
      out.print(desigV == null ? "" : desigV);
      out.write("\r\n");
      out.write("					</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<label for=\"department\">Department<span>*</span></label> <input\r\n");
      out.write("						id=\"dep\" type=\"text\" name=\"department\" placeholder=\"Department\"\r\n");
      out.write("						value=\"");
      out.print(depvalue == null ? "" : depvalue);
      out.write("\"> <span\r\n");
      out.write("						class=\"error\"> ");
      out.print(depV == null ? "" : depV);
      out.write("\r\n");
      out.write("					</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<label for=\"j_d\">Joined_date<span>*</span></label> <input id=\"j_d\"\r\n");
      out.write("						type=\"date\" name=\"joined_date\" placeholder=\"\"\r\n");
      out.write("						value=\"");
      out.print(joined_date_value == null ? "" : joined_date_value);
      out.write("\">\r\n");
      out.write("					<span class=\"error\"> ");
      out.print(joinedV == null ? "" : joinedV);
      out.write("\r\n");
      out.write("					</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<label for=\"salary\">Salary<span>*</span></label> <input id=\"sal\"\r\n");
      out.write("						type=\"text\" name=\"salary\" placeholder=\"Salary\"\r\n");
      out.write("						value=\"");
      out.print(salaryvalue == null ? "" : salaryvalue);
      out.write("\"> <span\r\n");
      out.write("						class=\"error\"> ");
      out.print(salaryV == null ? "" : salaryV);
      out.write("\r\n");
      out.write("					</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<label for=\"adr1\">Addressline1<span>*</span></label> <input\r\n");
      out.write("						id=\"adr1\" type=\"text\" name=\"addressline1\" placeholder=\"Address_1\"\r\n");
      out.write("						value=\"");
      out.print(adr1_value == null ? "" : adr1_value);
      out.write("\"> <span\r\n");
      out.write("						class=\"error\"> ");
      out.print(adr1V == null ? "" : adr1V);
      out.write("\r\n");
      out.write("					</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<label for=\"adr2\">Addressline2<span>*</span></label> <input\r\n");
      out.write("						id=\"adr2\" type=\"text\" name=\"addressline2\" placeholder=\"Address_2\"\r\n");
      out.write("						value=\"");
      out.print(adr2_value == null ? "" : adr2_value);
      out.write("\"> <span\r\n");
      out.write("						class=\"error\"> ");
      out.print(adr2V == null ? "" : adr2V);
      out.write("\r\n");
      out.write("					</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<label for=\"city\">City<span>*</span></label> <input id=\"ct\"\r\n");
      out.write("						type=\"text\" name=\"city\" placeholder=\"city\"\r\n");
      out.write("						value=\"");
      out.print(city_value == null ? "" : city_value);
      out.write("\"> <span\r\n");
      out.write("						class=\"error\"> ");
      out.print(cityV == null ? "" : cityV);
      out.write("\r\n");
      out.write("					</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<label for=\"state\">State<span>*</span></label> <input id=\"st\"\r\n");
      out.write("						type=\"text\" name=\"state\" placeholder=\"State\"\r\n");
      out.write("						value=\"");
      out.print(state_value == null ? "" : state_value);
      out.write("\"> <span\r\n");
      out.write("						class=\"error\"> ");
      out.print(stateV == null ? "" : stateV);
      out.write("\r\n");
      out.write("					</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<label for=\"country\">Country<span>*</span></label> <input id=\"con\"\r\n");
      out.write("						type=\"text\" name=\"country\" placeholder=\"Country\"\r\n");
      out.write("						value=\"");
      out.print(country_value == null ? "" : country_value);
      out.write("\"> <span\r\n");
      out.write("						class=\"error\"> ");
      out.print(countryV == null ? "" : countryV);
      out.write("\r\n");
      out.write("					</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"btn-block\">\r\n");
      out.write("					<button type=\"submit\">Update</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("	const dateField = document.getElementById('j_d');\r\n");
      out.write("\r\n");
      out.write("	// Get the current date in YYYY-MM-DD format\r\n");
      out.write("	const currentDate = new Date().toISOString().split('T')[0];\r\n");
      out.write("\r\n");
      out.write("	// Set the max attribute to the current date\r\n");
      out.write("	dateField.setAttribute('max', currentDate);\r\n");
      out.write("	\r\n");
      out.write("	console.log(\"Java script is running\");\r\n");
      out.write("	\r\n");
      out.write("  var error = '");
      out.print(request.getAttribute("error"));
      out.write("';\r\n");
      out.write("\r\n");
      out.write("  if (error) {\r\n");
      out.write("    var fieldToFocus = '");
      out.print(request.getAttribute("setFocus"));
      out.write("';\r\n");
      out.write("		 // Replace with the actual field ID\r\n");
      out.write("			document.getElementById(fieldToFocus).focus();\r\n");
      out.write("		}\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
