/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-08-08 16:01:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UserLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>User Login</title>\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("*{\r\n");
      out.write("  margin:0;\r\n");
      out.write("  padding:0;\r\n");
      out.write("  -webkit-box-sizing:border-box;\r\n");
      out.write("  -moz-box-sizing:border-box;\r\n");
      out.write("  box-sizing:border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("  font-family: 'Open Sans', sans-serif;\r\n");
      out.write("  background:#e2e2e2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("svg{\r\n");
      out.write("  position:fixed;\r\n");
      out.write("  top:10px;\r\n");
      out.write("  left:180px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container{\r\n");
      out.write("  position:relative;\r\n");
      out.write("  top:200px;\r\n");
      out.write("  left:35%;\r\n");
      out.write("  display:block;\r\n");
      out.write("  margin-bottom:80px;\r\n");
      out.write("  width:500px;\r\n");
      out.write("  height:400px;\r\n");
      out.write("  background:#fff;\r\n");
      out.write("  border-radius:5px;\r\n");
      out.write("  overflow:hidden;\r\n");
      out.write("  z-index:1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2{\r\n");
      out.write("  padding:40px;\r\n");
      out.write("  font-weight:lighter;\r\n");
      out.write("  text-transform:uppercase;\r\n");
      out.write("  color:#414141;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input{\r\n");
      out.write("  display:block;\r\n");
      out.write("  height:50px;\r\n");
      out.write("  width:90%;\r\n");
      out.write("  margin:0 auto;\r\n");
      out.write("  border:none;\r\n");
      out.write("  &::placeholder{\r\n");
      out.write("    -webkit-transform:translateY(0px);\r\n");
      out.write("      transform:translateY(0px);\r\n");
      out.write("    -webkit-transition:.5s;\r\n");
      out.write("      transition:.5s;\r\n");
      out.write("  }\r\n");
      out.write("  &:hover,\r\n");
      out.write("  &:focus,\r\n");
      out.write("  &:active:focus{\r\n");
      out.write("    color:#ff5722;\r\n");
      out.write("    outline:none;\r\n");
      out.write("    border-bottom:1px solid #ff5722;\r\n");
      out.write("    &::placeholder{\r\n");
      out.write("      color:#ff5722;\r\n");
      out.write("      position:relative;\r\n");
      out.write("      -webkit-transform:translateY(-20px);\r\n");
      out.write("      transform:translateY(-20px);\r\n");
      out.write("      \r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".email,\r\n");
      out.write(".pwd{\r\n");
      out.write("  position:relative;\r\n");
      out.write("  z-index:1;\r\n");
      out.write("  border-bottom:1px solid rgba(0,0,0,.1);\r\n");
      out.write("  padding-left:20px;\r\n");
      out.write("  font-family: 'Open Sans', sans-serif;\r\n");
      out.write("  color:#858585;\r\n");
      out.write("  font-weight:lighter;\r\n");
      out.write("  -webkit-transition:.5s;\r\n");
      out.write("  transition:.5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".link{\r\n");
      out.write("  text-decoration:none;\r\n");
      out.write("  display:inline-block;\r\n");
      out.write("  margin:27px 28%;\r\n");
      out.write("  color:#858585;\r\n");
      out.write("  font-weight:lighter;\r\n");
      out.write("  -webkit-transition:.5s;\r\n");
      out.write("  transition:.5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("button{\r\n");
      out.write("  cursor:pointer; \r\n");
      out.write("  display:inline-block;\r\n");
      out.write("  float:left;\r\n");
      out.write("  width:250px;\r\n");
      out.write("  height:60px;\r\n");
      out.write("  margin-top:-10px;\r\n");
      out.write("  border:none;\r\n");
      out.write("  font-family: 'Open Sans', sans-serif;\r\n");
      out.write("  text-transform:uppercase;\r\n");
      out.write("  color:#fff;\r\n");
      out.write("  -webkit-transition:.5s;\r\n");
      out.write("  transition:.5s;\r\n");
      out.write(" \r\n");
      out.write("    background:#673ab7;\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  span{\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    display:block;\r\n");
      out.write("    margin:-10px 20%;\r\n");
      out.write("    -webkit-transform:translateX(0);\r\n");
      out.write("    transform:translateX(0);\r\n");
      out.write("    -webkit-transition:.5s;\r\n");
      out.write("    transition:.5s;\r\n");
      out.write("  }\r\n");
      out.write("  &:hover{\r\n");
      out.write("    span{\r\n");
      out.write("      -webkit-transform:translateX(30px);\r\n");
      out.write("      transform:translateX(30px);\r\n");
      out.write("      }\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".reg{\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    top:0;\r\n");
      out.write("    left:0;\r\n");
      out.write("    -webkit-transform:translateY(-100%) scale(1);\r\n");
      out.write("    transform:translateY(-100%) scale(1);\r\n");
      out.write("    display:block;\r\n");
      out.write("    width:20px;\r\n");
      out.write("    height:20px;\r\n");
      out.write("    border-radius:50px;\r\n");
      out.write("    background:#673ab7;\r\n");
      out.write("    z-index:5;\r\n");
      out.write("    -webkit-transition:.8s ease-in-out;\r\n");
      out.write("    transition:.8s ease-in-out;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".sig{\r\n");
      out.write("   position:absolute;\r\n");
      out.write("   top:0;\r\n");
      out.write("   right:0;\r\n");
      out.write("   -webkit-transform:translateY(-100%) scale(1);\r\n");
      out.write("   transform:translateY(-100%) scale(1);\r\n");
      out.write("   display:block;\r\n");
      out.write("   width:20px;\r\n");
      out.write("   height:20px;\r\n");
      out.write("   display:block;\r\n");
      out.write("   background:#ff5722;\r\n");
      out.write("   z-index:5;\r\n");
      out.write("   -webkit-transition:.8s ease-in-out;\r\n");
      out.write("    transition:.8s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h3{\r\n");
      out.write("  position:absolute;\r\n");
      out.write("  top:-100%;\r\n");
      out.write("  left:20%; \r\n");
      out.write("  text-transform:uppercase;\r\n");
      out.write("  font-weight:bolder;\r\n");
      out.write("  color:rgba(255,255,255,.3);\r\n");
      out.write("  -webkit-transition:.3s ease-in-out 1.2s;\r\n");
      out.write("  transition:.3s ease-in-out 1.2s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".error{\r\n");
      out.write("color:red;\r\n");
      out.write("font-weight: bold;\r\n");
      out.write("font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".register{\r\n");
      out.write("background:#ff5722;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span{\r\n");
      out.write("display: flex;\r\n");
      out.write("justify-content: center;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".err{\r\n");
      out.write("margin:0;\r\n");
      out.write("display:flex;\r\n");
      out.write("justify-content: center;\r\n");
      out.write("color:red;\r\n");
      out.write("font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" .toggle-password {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 50%;\r\n");
      out.write("        right: 5px;\r\n");
      out.write("        transform: translateY(-50%);\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");


String emailvalue = (String) request.getAttribute("email");
String passvalue = (String) request.getAttribute("password");
String emailV = (String) request.getAttribute("emailErr");
String passV = (String) request.getAttribute("passErr");
String chan = (String) request.getAttribute("changed1");



      out.write("\r\n");
      out.write("\r\n");
      out.write("<svg version=\"1.1\" id=\"Layer_1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" x=\"0px\" y=\"0px\"\r\n");
      out.write("	 width=\"800px\" height=\"600px\" viewBox=\"0 0 800 600\" enable-background=\"new 0 0 800 600\" xml:space=\"preserve\">\r\n");
      out.write("<linearGradient id=\"SVGID_1_\" gradientUnits=\"userSpaceOnUse\" x1=\"174.7899\" y1=\"186.34\" x2=\"330.1259\" y2=\"186.34\" gradientTransform=\"matrix(0.8538 0.5206 -0.5206 0.8538 147.9521 -79.1468)\">\r\n");
      out.write("	<stop  offset=\"0\" style=\"stop-color:#FFC035\"/>\r\n");
      out.write("	<stop  offset=\"0.221\" style=\"stop-color:#F9A639\"/>\r\n");
      out.write("	<stop  offset=\"1\" style=\"stop-color:#E64F48\"/>\r\n");
      out.write("</linearGradient>\r\n");
      out.write("<circle fill=\"url(#SVGID_1_)\" cx=\"266.498\" cy=\"211.378\" r=\"77.668\"/>\r\n");
      out.write("<linearGradient id=\"SVGID_2_\" gradientUnits=\"userSpaceOnUse\" x1=\"290.551\" y1=\"282.9592\" x2=\"485.449\" y2=\"282.9592\">\r\n");
      out.write("	<stop  offset=\"0\" style=\"stop-color:#FFA33A\"/>\r\n");
      out.write("	<stop  offset=\"0.0992\" style=\"stop-color:#E4A544\"/>\r\n");
      out.write("	<stop  offset=\"0.9624\" style=\"stop-color:#00B59C\"/>\r\n");
      out.write("</linearGradient>\r\n");
      out.write("<circle fill=\"url(#SVGID_2_)\" cx=\"388\" cy=\"282.959\" r=\"97.449\"/>\r\n");
      out.write("<linearGradient id=\"SVGID_3_\" gradientUnits=\"userSpaceOnUse\" x1=\"180.3469\" y1=\"362.2723\" x2=\"249.7487\" y2=\"362.2723\">\r\n");
      out.write("	<stop  offset=\"0\" style=\"stop-color:#12B3D6\"/>\r\n");
      out.write("	<stop  offset=\"1\" style=\"stop-color:#7853A8\"/>\r\n");
      out.write("</linearGradient>\r\n");
      out.write("<circle fill=\"url(#SVGID_3_)\" cx=\"215.048\" cy=\"362.272\" r=\"34.701\"/>\r\n");
      out.write("<linearGradient id=\"SVGID_4_\" gradientUnits=\"userSpaceOnUse\" x1=\"367.3469\" y1=\"375.3673\" x2=\"596.9388\" y2=\"375.3673\">\r\n");
      out.write("	<stop  offset=\"0\" style=\"stop-color:#12B3D6\"/>\r\n");
      out.write("	<stop  offset=\"1\" style=\"stop-color:#7853A8\"/>\r\n");
      out.write("</linearGradient>\r\n");
      out.write("<circle fill=\"url(#SVGID_4_)\" cx=\"482.143\" cy=\"375.367\" r=\"114.796\"/>\r\n");
      out.write("<linearGradient id=\"SVGID_5_\" gradientUnits=\"userSpaceOnUse\" x1=\"365.4405\" y1=\"172.8044\" x2=\"492.4478\" y2=\"172.8044\" gradientTransform=\"matrix(0.8954 0.4453 -0.4453 0.8954 127.9825 -160.7537)\">\r\n");
      out.write("	<stop  offset=\"0\" style=\"stop-color:#FFA33A\"/>\r\n");
      out.write("	<stop  offset=\"1\" style=\"stop-color:#DF3D8E\"/>\r\n");
      out.write("</linearGradient>\r\n");
      out.write("<circle fill=\"url(#SVGID_5_)\" cx=\"435.095\" cy=\"184.986\" r=\"63.504\"/>\r\n");
      out.write("</svg>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <h2>login</h2>\r\n");
      out.write(" \r\n");
      out.write(" 	 <div class=\"err\">\r\n");
      out.write("    <h5>\r\n");
      out.write("    ");
 
        if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("              ");
      out.print( request.getAttribute("error") );
      out.write("\r\n");
      out.write("        ");
 }
        if(request.getAttribute("success")!=null){
      out.write("\r\n");
      out.write("        ");
      out.print( request.getAttribute("success") );
      out.write("\r\n");
      out.write("        ");
 request.setAttribute("success",null); 
      out.write("\r\n");
      out.write("        ");
 }
      
        
      out.write("\r\n");
      out.write("    </h5>\r\n");
      out.write("</div>\r\n");
      out.write(" \r\n");
      out.write("  <form method=\"post\" action=\"UserLogin\">\r\n");
      out.write("    <input id =\"email_ID\" type=\"text\" class=\"email\" placeholder=\"Email\" name=\"email_id\"\r\n");
      out.write("    value=\"");
      out.print( emailvalue == null ? "" : emailvalue );
      out.write("\">\r\n");
      out.write("    <div class=\"span\">\r\n");
      out.write("<span class=\"error\">\r\n");
      out.write(" ");
      out.print( emailV == null ? "" : emailV );
      out.write("\r\n");
      out.write("</span>\r\n");
      out.write("</div>\r\n");
      out.write("    <br/>\r\n");
      out.write("    <input type=\"password\" class=\"pwd\" placeholder=\"Password\" name=\"password\"\r\n");
      out.write("    value=\"");
      out.print( passvalue == null ? "" : passvalue );
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"span\">\r\n");
      out.write("<span class=\"error\">\r\n");
      out.write(" ");
      out.print( passV == null ? "" : passV );
      out.write("\r\n");
      out.write("</span>\r\n");
      out.write("</div>\r\n");
      out.write("  \r\n");
      out.write("  <a href=\"userForgotPass.jsp\" class=\"link\">\r\n");
      out.write("    Forgot Password ?\r\n");
      out.write("  </a>\r\n");
      out.write("  <br/>\r\n");
      out.write("  <button class=\"signin\">\r\n");
      out.write("    <span>Sign in</span>\r\n");
      out.write("  </button></form>\r\n");
      out.write("  <form method=\"post\" action=\"signUp.jsp\">\r\n");
      out.write("  <button class=\"register\">\r\n");
      out.write("    <span>Register</span>\r\n");
      out.write("  </button>\r\n");
      out.write("  </form>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    var error = '");
      out.print( request.getAttribute("error") );
      out.write("';\r\n");
      out.write("\r\n");
      out.write("    if (error) {\r\n");
      out.write("      var fieldToFocus = '");
      out.print(request.getAttribute("setFocus"));
      out.write(" '; \r\n");
      out.write("      // Replace with the actual field ID\r\n");
      out.write("      document.getElementById(fieldToFocus).focus();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function togglePasswordVisibility() {\r\n");
      out.write("        var passwordField = document.getElementById('password');\r\n");
      out.write("        var eyeIcon = document.querySelector('.toggle-password');\r\n");
      out.write("\r\n");
      out.write("        if (passwordField.type === 'password') {\r\n");
      out.write("            passwordField.type = 'text';\r\n");
      out.write("            eyeIcon.classList.remove('fa-eye');\r\n");
      out.write("            eyeIcon.classList.add('fa-eye-slash');\r\n");
      out.write("        } else {\r\n");
      out.write("            passwordField.type = 'password';\r\n");
      out.write("            eyeIcon.classList.remove('fa-eye-slash');\r\n");
      out.write("            eyeIcon.classList.add('fa-eye');\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    $(document).ready(() => {\r\n");
      out.write("  	  /*------- button with class register -------*/\r\n");
      out.write("  	  let reg_btn:string = $('.container .register')\r\n");
      out.write("  	  \r\n");
      out.write("  	  /*------- button with class sign in --------*/\r\n");
      out.write("  	  let sig_btn:string = $('.container .signin')\r\n");
      out.write("  	  \r\n");
      out.write("  	  /*------- back button ----------------------*/\r\n");
      out.write("  	  let back_btn:string = $('.container .back')\r\n");
      out.write("  	  \r\n");
      out.write("\r\n");
      out.write("  	  \r\n");
      out.write("\r\n");
      out.write("  	  reg_btn.click(function(e){\r\n");
      out.write("  	    e.preventDefault()\r\n");
      out.write("  	    $(this).siblings('.reg').css({\r\n");
      out.write("  	      'transform':'translateY(40%) scale(5)',\r\n");
      out.write("  	      'border-radius':'0',\r\n");
      out.write("  	      'width':'100%',\r\n");
      out.write("  	      'height':'100%'\r\n");
      out.write("  	    }).end();\r\n");
      out.write("  	    \r\n");
      out.write("  	  \r\n");
      out.write("  	    reg_btn.siblings('.container h3:nth-of-type(1)').css({\r\n");
      out.write("  	      'top':'40%',\r\n");
      out.write("  	      'z-index':'8',\r\n");
      out.write("  	    }).end().end();   \r\n");
      out.write("  	  });\r\n");
      out.write("  	  \r\n");
      out.write("  	   sig_btn.on('click',function(e){\r\n");
      out.write("  	    e.preventDefault();\r\n");
      out.write("  	    $(this).siblings('.sig').css({\r\n");
      out.write("  	      'transform':'translateY(40%) scale(5)',\r\n");
      out.write("  	      'border-radius':'0',\r\n");
      out.write("  	      'width':'100%',\r\n");
      out.write("  	      'height':'100%'\r\n");
      out.write("  	    }).end();\r\n");
      out.write("  	     \r\n");
      out.write("  	 \r\n");
      out.write("  	    sig_btn.siblings('.container h3:nth-of-type(2)').css({\r\n");
      out.write("  	      'top':'40%',\r\n");
      out.write("  	      'z-index':'8',\r\n");
      out.write("  	    }).end().end(); \r\n");
      out.write("  	    \r\n");
      out.write("  	  });\r\n");
      out.write("  	});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
